services:
  url-tocsv:
    image: url-tocsv:build
    build: https://github.com/jtagcat/url-tocsv#main
    volumes:
      - ./xyz:/wd/data
    environment:
      - URL=https://services.postimees.ee/radio/v1/elmar
      - PERIOD=20s
    restart: unless-stopped
